version: 2
jobs:
  lint:
    docker:
      - image: cimg/rust:1.46.0-node
    steps:
      - checkout
      - run:
          command: yarn
      - run:
          name: Lint
          command: yarn lint

workflows:
  version: 2
  tests:
    jobs:
      - lint
